M48
; DRILL file {KiCad 9.0.7} date 2026-03-08T21:34:52-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-08T21:34:52-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X117.375Y-74.65
X117.375Y-124.65
X167.375Y-74.65
X167.375Y-124.65
M30
